# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.BooleanField(default=False)),
                ('player_class', models.PositiveSmallIntegerField(choices=[(1, 'player'), (2, 'visitor'), (3, 'junior player'), (4, 'beginner player')], default=1)),
                ('quaterly_games_per_week', models.PositiveSmallIntegerField(choices=[(0, 'no quarterly'), (1, 'one game per week quarterly'), (2, 'two games per week quarterly'), (3, 'three games per week quarterly'), (4, 'four games per week quarterly')], default=0)),
                ('game_cost', models.FloatField()),
                ('quarter_cost', models.FloatField()),
                ('free_games', models.SmallIntegerField()),
                ('half_cost_games', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerQuarterCostRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prorate', models.FloatField()),
                ('cost_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.CostRule')),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='game',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='player',
        ),
        migrations.AddField(
            model_name='game',
            name='attendees',
            field=models.ManyToManyField(to='attendance.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='pool',
            field=models.IntegerField(choices=[(1, 'Carmody'), (2, 'VMAC')], default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.AddField(
            model_name='playerquartercostrule',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Player'),
        ),
        migrations.AddField(
            model_name='playerquartercostrule',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Quarter'),
        ),
        migrations.AlterUniqueTogether(
            name='playerquartercostrule',
            unique_together=set([('player', 'quarter')]),
        ),
    ]
