# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20160501_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costrule',
            old_name='quaterly_games_per_week',
            new_name='quarterly_games_per_week',
        ),
    ]
