# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20160501_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerquartercostrule',
            name='quarter',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='Quarter',
        ),
    ]
