# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20160502_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attendees',
            field=models.ManyToManyField(blank=True, null=True, to='attendance.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='shared_time_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='playerquartercostrule',
            name='prorate',
            field=models.FloatField(default=1.0),
        ),
    ]
