# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20160504_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='attendance.Player'),
        ),
    ]
