# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20160504_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'check'), (2, 'PayPal'), (3, 'to Chris'), (4, 'cash'), (5, 'account credit')], default=4)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Player')),
            ],
        ),
    ]
