# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_othercharges_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherCharges',
            new_name='OtherCharge',
        ),
    ]
