# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-02 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20160604_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costrule',
            name='student',
        ),
        migrations.AddField(
            model_name='costrule',
            name='covered_games_per_quarter',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerquartercostrule',
            name='start_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='costrule',
            name='free_games',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costrule',
            name='game_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='costrule',
            name='half_cost_games',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costrule',
            name='player_class',
            field=models.PositiveSmallIntegerField(choices=[(1, 'player'), (2, 'student'), (3, 'junior player')], default=1),
        ),
        migrations.AlterField(
            model_name='costrule',
            name='quarter_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='othercharge',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='playerquartercostrule',
            name='quarter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
