# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-07 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20161001_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerquartercostrule',
            name='start_num_games',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
