# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-18 03:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0010_playerquartercostrule_start_num_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costrule',
            name='player_class',
            field=models.PositiveSmallIntegerField(choices=[(1, 'regular player'), (2, 'student'), (3, 'junior player')], default=1),
        ),
    ]
