# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-20 04:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('attendance', '0011_auto_20161017_2112'), ('attendance', '0012_auto_20161017_2133'), ('attendance', '0013_auto_20161017_2140'), ('attendance', '0014_auto_20161017_2144'), ('attendance', '0015_auto_20161017_2153'), ('attendance', '0016_remove_player_user')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0010_playerquartercostrule_start_num_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costrule',
            name='player_class',
            field=models.PositiveSmallIntegerField(choices=[(1, 'regular player'), (2, 'student'), (3, 'junior player')], default=1),
        ),
    ]
