# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-21 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('attendance', '0012_player_user'), ('attendance', '0013_remove_player_user')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0011_auto_20161017_2112_squashed_0016_remove_player_user'),
    ]

    operations = [
    ]
