# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-21 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
