# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-27 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20161021_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='costrule',
            name='is_visitor',
            field=models.BooleanField(default=False),
        ),
    ]
