# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-20 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20161017_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
