# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-05 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_costrule_is_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.AlterUniqueTogether(
            name='costrule',
            unique_together=set([('player_class', 'is_visitor', 'quarterly_games_per_week')]),
        ),
    ]
