# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-06 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_auto_20161105_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costrule',
            name='quarterly_games_per_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'no quarterly'), (1, 'one game per week quarterly'), (2, 'two games per week quarterly'), (3, 'three games per week quarterly'), (4, 'four games per week quarterly'), (5, 'five games per week quarterly')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='pool',
            field=models.IntegerField(choices=[(1, 'Carmody'), (2, 'VMAC'), (3, 'EPIC')], default=1),
        ),
    ]
