# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-06-28 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_auto_20170205_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='costrule',
            name='first_valid_quarter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='costrule',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'check'), (2, 'PayPal'), (3, 'to Chris'), (4, 'cash'), (5, 'account credit'), (6, 'direct deposit')], default=4),
        ),
        migrations.AlterUniqueTogether(
            name='costrule',
            unique_together=set([('player_class', 'is_visitor', 'quarterly_games_per_week', 'first_valid_quarter')]),
        ),
    ]
